name: rahul_s_application1
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.1
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.0
  connectivity_plus: ^1.4.0
  shared_preferences: ^2.0.7
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/robotorobotoromanlight300.ttf
          weight: 300
        - asset: assets/fonts/robotorobotoromanmedium500.ttf
          weight: 500
        - asset: assets/fonts/robotorobotoromanregular400.ttf
          weight: 400
        - asset: assets/fonts/robotorobotoromanbold700.ttf
          weight: 700
        - asset: assets/fonts/robotorobotoitaliclight300.ttf
          weight: 300
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/opensansopensansromanbold700.ttf
          weight: 700
        - asset: assets/fonts/opensansopensansromansemibold600.ttf
          weight: 600
        - asset: assets/fonts/opensansopensansromanextrabold800.ttf
          weight: 800
        - asset: assets/fonts/opensansopensansromanlight300.ttf
          weight: 300
        - asset: assets/fonts/opensansopensansromanregular400.ttf
          weight: 400
    - family: Roboto Slab
      fonts: 
        - asset: assets/fonts/robotoslabregular400.ttf
          weight: 400
        - asset: assets/fonts/robotoslabextrabold800.ttf
          weight: 800
        - asset: assets/fonts/robotoslablight300.ttf
          weight: 300
        - asset: assets/fonts/robotoslabbold700.ttf
          weight: 700
    - family: Prata
      fonts: 
        - asset: assets/fonts/prataregular400.ttf
          weight: 400
    - family: Roboto Mono
      fonts: 
        - asset: assets/fonts/robotomonoregular300.ttf
          weight: 300
        - asset: assets/fonts/robotomonoregular500.ttf
          weight: 500
        - asset: assets/fonts/robotomonoregular400.ttf
          weight: 400
        - asset: assets/fonts/robotomonoregular700.ttf
          weight: 700
    - family: Inter
      fonts: 
        - asset: assets/fonts/intersemibold400.ttf
          weight: 400
        - asset: assets/fonts/interlight300.ttf
          weight: 300
